# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/project/finder/parts/matrix_mul_vivado/work_vivado/matrix_mul_vivado.srcs/sources_1/ip/mult_W18/mult_W18.xci
# IP: The module: 'mult_W18' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/project/finder/parts/matrix_mul_vivado/work_vivado/matrix_mul_vivado.srcs/sources_1/ip/mult_W18/mult_W18_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_W18'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/project/finder/parts/matrix_mul_vivado/work_vivado/matrix_mul_vivado.srcs/sources_1/ip/mult_W18/mult_W18.xci
# IP: The module: 'mult_W18' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/project/finder/parts/matrix_mul_vivado/work_vivado/matrix_mul_vivado.srcs/sources_1/ip/mult_W18/mult_W18_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_W18'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
